import unittest

from verification import encoding as enc


class NamedEncoderGoldenTests(unittest.TestCase):
    """Literals below were calculated from fields, not generated by the ISS."""

    def test_original_rom_literals(self):
        actual = [
            enc.addi(1, 0, 5),
            enc.addi(2, 0, 10),
            enc.add(3, 1, 2),
            enc.sw(3, 0, 0),
            enc.lw(4, 0, 0),
            enc.addi(4, 4, 1),
            enc.sw(4, 4, 0),
            enc.lw(5, 4, 0),
            enc.beq(5, 0, -5),
        ]
        self.assertEqual(actual, [
            0x20010005, 0x2002000A, 0x00221820,
            0xAC030000, 0x8C040000, 0x20840001,
            0xAC040004, 0x8C050004, 0x10A0FFFB,
        ])

    def test_all_r_type_encodings(self):
        functions = [
            (enc.add, 0x20), (enc.addu, 0x21),
            (enc.sub, 0x22), (enc.subu, 0x23),
            (enc.and_, 0x24), (enc.or_, 0x25),
            (enc.xor_, 0x26), (enc.nor, 0x27), (enc.slt, 0x2A),
        ]
        for function, funct in functions:
            with self.subTest(function=function.__name__):
                self.assertEqual(function(3, 1, 2), 0x00221800 | funct)
        self.assertEqual(enc.sll(3, 2, 4), 0x00021900)
        self.assertEqual(enc.srl(3, 2, 4), 0x00021902)
        self.assertEqual(enc.sra(3, 2, 4), 0x00021903)
        self.assertEqual(enc.nop(), 0x00000000)

    def test_immediate_memory_and_control_encodings(self):
        expected = {
            enc.andi(2, 1, 0x80FF): 0x302280FF,
            enc.ori(2, 1, 0x80FF): 0x342280FF,
            enc.xori(2, 1, 0x80FF): 0x382280FF,
            enc.lui(2, 0xABCD): 0x3C02ABCD,
            enc.lb(2, 3, 1): 0x80220003,
            enc.lh(2, 2, 1): 0x84220002,
            enc.lw(2, 4, 1): 0x8C220004,
            enc.lbu(2, 3, 1): 0x90220003,
            enc.lhu(2, 2, 1): 0x94220002,
            enc.sb(2, 3, 1): 0xA0220003,
            enc.sh(2, 2, 1): 0xA4220002,
            enc.sw(2, 4, 1): 0xAC220004,
            enc.beq(1, 2, -2): 0x1022FFFE,
            enc.bne(1, 2, -2): 0x1422FFFE,
            enc.j(0x40, 0): 0x08000010,
            enc.jal(0x40, 0): 0x0C000010,
            enc.eret(): 0x60000000,
        }
        for actual, golden in expected.items():
            self.assertEqual(actual, golden)

    def test_range_and_jump_region_checks(self):
        with self.assertRaises(enc.EncodingError):
            enc.add(32, 0, 0)
        with self.assertRaises(enc.EncodingError):
            enc.addi(1, 0, 32768)
        with self.assertRaises(enc.EncodingError):
            enc.ori(1, 0, -1)
        with self.assertRaises(enc.EncodingError):
            enc.sll(1, 2, 32)
        with self.assertRaises(enc.EncodingError):
            enc.j(3, 0)
        with self.assertRaises(enc.EncodingError):
            enc.j(0x20000000, 0x10000000)


class AssemblerTests(unittest.TestCase):
    def test_two_pass_labels_numeric_branch_and_org(self):
        image = enc.assemble(
            """
                start: addi r1, r0, 2
                loop:  addi $1, $1, -1
                       bne r1, zero, loop
                       jal done
                       nop
                .org 0x80
                done:  eret
            """
        )
        self.assertEqual(image.labels, {"start": 0, "loop": 4, "done": 0x80})
        self.assertEqual(image.words[0], 0x20010002)
        self.assertEqual(image.words[4], 0x2021FFFF)
        self.assertEqual(image.words[8], 0x1420FFFE)
        self.assertEqual(image.words[12], 0x0C000020)
        self.assertEqual(image.words[16], 0)
        self.assertEqual(image.words[0x80], 0x60000000)
        dense = image.dense_words(start=0, end=0x84)
        self.assertEqual(len(dense), 33)
        self.assertTrue(all(word == 0 for word in dense[5:32]))

    def test_original_program_assembly_matches_rom(self):
        source = """
            addi r1,r0,5
            addi r2,r0,10
            add r3,r1,r2
            sw r3,0(r0)
            lw r4,0(r0)
            addi r4,r4,1
            sw r4,4(r0)
            lw r5,4(r0)
            beq r5,r0,-5
        """
        self.assertEqual(enc.assemble(source).dense_words(), [
            0x20010005, 0x2002000A, 0x00221820,
            0xAC030000, 0x8C040000, 0x20840001,
            0xAC040004, 0x8C050004, 0x10A0FFFB,
        ])

    def test_assembler_rejects_bad_sources(self):
        bad_sources = [
            "label: nop\nlabel: nop",
            ".org 3\nnop",
            "lw r1, 4, r2",
            "unknown r1,r2,r3",
            "add r1,r2",
            "addi r1,r0,0x10000",
            ".org 0\nnop\n.org 0\nnop",
        ]
        for source in bad_sources:
            with self.subTest(source=source), self.assertRaises(enc.EncodingError):
                enc.assemble(source)


if __name__ == "__main__":
    unittest.main()
